#!/bin/sh
# Keep this as simple as possible, moving Maildir messages is tricky
# I'm using the alternative uid map which seems more resistant to moving than the native
source $HOME/.config/notmuch/hooks/common

# Move spam classifieds to learn
$NM search --exclude=false --output=files 'tag:spam and not folder:Junk and not folder:Learn/Spam' | xargs -n1 -i{} mv -f "{}" $MAILDIR/Learn/Spam/cur/
