#!/bin/sh
# Keep this as simple as possible, moving Maildir messages is tricky
# I'm using the alternative uid map which seems more resistant to moving than the native
source $HOME/.config/notmuch/hooks/common

# Move deleted messages to the Trash folder
$NM search --output=files 'tag:deleted and not folder:Trash' | xargs -n1 -i{} mv -f "{}" $MAILDIR/Trash/
