#!/bin/sh
# Get our common stuff
source $HOME/.config/notmuch/hooks/common

# Read current database revision
CUR_REV=`nm_get_dbrevision`
LAST_REV=`nm_get_lastnotifiedrev`

# What to notify, the prefined query shows the max. available messages, not
# counting the last time we notified, so it just has a list of things
# we didn't handle yet in the MUA
Q="query:notify and lastmod:$LAST_REV..$CUR_REV"

# How many entries maximum?
N=5

ICON='/usr/share/icons/Faenza/apps/48/internet-mail.png'

# the sort order of subjects
SORT="newest-first"


# have notmuch count the number of messages in the search
CNT=$($NM count --output=messages "$Q")
if [ "$CNT" -gt 0 ]; then
  # have notmuch pull the specified number of mail subjects from the search.
  # also, do some rough formatting of the result, to pull thread string,
  # sender etc. leaving just the subject text.
  TXT_SUBS=$($NM search --format=text --output=summary --limit="$N" --sort="$SORT" "$Q" | sed 's/^[^;]*; //' | sed 's/$/\n'/)
  # special characters like @, &, (, ), etc. break notify-send
  # however it likes HTML encoding just fine, so use recode.
  HTML_SUBS=$(echo "$TXT_SUBS" | recode UTF-8..html)

  notify-send -i "$ICON" "$CNT unread mesages." "$HTML_SUBS"
fi

# Save the revision of the database, so we can use it next time
nm_set_lastnotifiedrev $CUR_REV

exit 0
