#!/bin/sh

# Hook invoked by new command after messages have been imported and
# initial tags have been applied typically used for:
# - signal programs we're done syncing
# - postprocessing like additional tagging
echo "Post new hook..."
source $HOME/.config/notmuch/hooks/common

# Initial tags are already in place (see config of notmuch)
# now do additional processing
echo "Additional tagging..."
$NM tag --batch --input=$HOOKS/tag/incoming

# Run afew for advanced processing
echo "Running afew for advanced processing..."
$AF --new --tag
# As of notmuch 0.25 the 'lists' tag has no added value
# because we can match on regular expressions now.
# TODO: adapt afew instead of doing it here
$NM tag -lists tag:lists


# Signal astroid we're done
if pgrep -x "astroid" > /dev/null
then
    echo "Detected running astroid, stop polling"
    $AS --stop-polling
fi

# Notify
echo "Notifying..."
$HOOKS/notifynew
