#!/bin/sh

# Hook invoked by new command after messages have been imported and
# initial tags have been applied typically used for:
# - signal programs we're done syncing
# - postprocessing like additional tagging
echo "Post new hook..."
source $HOME/.config/notmuch/hooks/common

# Initial tags are already in place (see config of notmuch)
# now do additional processing
echo "Additional tagging..."
$NM tag --batch --input=$HOOKS/tag/incoming

# Run afew for advanced processing
echo "Running afew for advanced processing..."
$AF --new --tag
# Stuff that the server thinks is a list we trust that
$NM tag +lists folder:Lists
# Odoo does not set its List-ID header properly
$NM tag +lists/odoo 'folder:Lists/odoo'

# Signal astroid we're done
if pgrep -x "astroid" > /dev/null
then
    echo "Detected running astroid, stop polling"
    $AS --stop-polling
fi

# Notify
echo "Notifying..."
$HOOKS/notifynew
