#!/bin/sh

# Hook run by the new command before anything happens
#
# Typically used for:
# - signal others we're going to sync
# - run something which actually fetches the mail?
# - do anything that requires running notmuch new afterwards, had it been run manually, so it will
#   taken care of directly (this is the pre-new hook)
#
echo "Pre-new hook..."
source $HOME/.config/notmuch/hooks/common

if pgrep -x "astroid" > /dev/null
then
    echo "Detected running astroid, start polling"
    $ASTROID --start-polling
fi

# Actually get the new stuff
$MB -a

# Move deleted items to Trash
echo "Moving deleted items to Trash..."
$HOOKS/movetotrash

# Move spams which are not Junk already to Learn
echo "Learning new spam..."
$HOOKS/learnspam
