#!/bin/bash

#
# $1   : tag
# $2   : 'thread:<ID> or 'id:<ID>'
# <ID> : when viewing a thread: thread id
#        when viewing a message: message id



if [[ $(notmuch search $2 and tag:$1) ]]; then # check if the message matches the tag
  echo "removing tag: $1 from $2"              # 
  notmuch tag -$1 $2                           # remove the tag
else
  echo "adding tag: $1 to $2"                  #
  notmuch tag +$1 $2                           # add the tag
fi
